# Generated by Django 3.1.7 on 2021-04-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=100)),
                ('asset_sn', models.CharField(default='00', max_length=10)),
                ('place_from', models.CharField(max_length=100)),
                ('place_to', models.CharField(max_length=100)),
                ('receivers_name', models.CharField(max_length=100)),
                ('receivers_id', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('confirmed_by', models.CharField(max_length=100)),
                ('form_user', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form_form',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_user_id_id', models.CharField(max_length=100, null=True)),
                ('document_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Form.form')),
            ],
        ),
    ]
